"""empty message

Revision ID: 3cabdbfecf2b
Revises: 3b3383736546
Create Date: 2015-02-01 12:33:36.456235

"""

# revision identifiers, used by Alembic.
revision = '3cabdbfecf2b'
down_revision = '3b3383736546'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
