"""initial migration

Revision ID: 22f24f45c754
Revises: None
Create Date: 2015-01-28 20:57:14.448610

"""

# revision identifiers, used by Alembic.
revision = '22f24f45c754'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    ### end Alembic commands ###
